"""add column to teachers

Revision ID: 085e0eb38323
Revises: d3dc6d84495a
Create Date: 2025-11-18 12:00:03.065743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085e0eb38323'
down_revision = 'd3dc6d84495a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_homeroom_teacher', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('is_homeroom_teacher')

    # ### end Alembic commands ###
