"""up column student lesson period

Revision ID: 0a6e499fec31
Revises: 2578fac4a7d5
Create Date: 2025-10-18 23:10:22.639792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6e499fec31'
down_revision = '2578fac4a7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_lesson_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'period', ['period_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_lesson_period', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('period_id')

    # ### end Alembic commands ###
