"""create student class

Revision ID: 0bd79631b1d9
Revises: 0a6e499fec31
Create Date: 2025-10-19 10:49:05.213224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd79631b1d9'
down_revision = '0a6e499fec31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_room_id'], ['class_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('students_class_room_id_fkey'), type_='foreignkey')
        batch_op.drop_column('class_room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_room_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('students_class_room_id_fkey'), 'class_room', ['class_room_id'], ['id'], ondelete='CASCADE')

    op.drop_table('student_class')
    # ### end Alembic commands ###
