"""update cloud

Revision ID: 0c802822a40f
Revises: 25f33433d021
Create Date: 2025-10-03 12:27:49.609270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c802822a40f'
down_revision = '25f33433d021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_status', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('cloud_class_room_id_fkey'), type_='foreignkey')
        batch_op.drop_column('class_room_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('class_room_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('cloud_class_room_id_fkey'), 'class_room', ['class_room_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('file_status')

    # ### end Alembic commands ###
