"""update Score_Type 2

Revision ID: 0fef3924c39f
Revises: 189931130f7f
Create Date: 2025-11-08 00:12:41.097218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fef3924c39f'
down_revision = '189931130f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_type', schema=None) as batch_op:
        batch_op.drop_column('max_count')

    # ### end Alembic commands ###
