"""update student year summary with addition transfer_info

Revision ID: 10b2e8410f38
Revises: 2117d5cf1c18
Create Date: 2025-11-28 16:28:24.018871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b2e8410f38'
down_revision = '2117d5cf1c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_year_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_info', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_year_summary', schema=None) as batch_op:
        batch_op.drop_column('transfer_info')

    # ### end Alembic commands ###
