"""update users and create tmp_token

Revision ID: 1406b5223e08
Revises: ffe56d1737dd
Create Date: 2025-09-27 15:09:57.411716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1406b5223e08'
down_revision = 'ffe56d1737dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('token_expire', sa.DateTime(), nullable=True),
    sa.Column('token_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token')
        batch_op.drop_column('token_expire')
        batch_op.drop_column('token_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token_expire', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('tmp_token')
    # ### end Alembic commands ###
