"""update tmp_token

Revision ID: 14b9c1f96c76
Revises: 1406b5223e08
Create Date: 2025-09-27 16:27:28.406209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14b9c1f96c76'
down_revision = '1406b5223e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmp_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expire_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.drop_column('token_expire')
        batch_op.drop_column('token_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmp_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token_expire', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('expire_at')

    # ### end Alembic commands ###
