"""update students

Revision ID: 1632370a76ea
Revises: 232ff0351ad5
Create Date: 2025-10-17 12:20:12.595107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1632370a76ea'
down_revision = '232ff0351ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('BOD', sa.Date(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_code', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('student_code')

    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.drop_column('BOD')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
