"""update Score 2

Revision ID: 189931130f7f
Revises: f89aadfeea3a
Create Date: 2025-11-07 22:09:07.721498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189931130f7f'
down_revision = 'f89aadfeea3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'score_type', ['score_type_id'], ['id'], ondelete='NO ACTION')
        batch_op.drop_column('score_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_type', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('score_type_id')

    # ### end Alembic commands ###
