"""update monitoring

Revision ID: 1a8071bc7ce4
Revises: bfc3e726450b
Create Date: 2025-09-16 14:47:22.178780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8071bc7ce4'
down_revision = 'bfc3e726450b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum('SUCCESS', 'FAIL', 'WARNING', name='status')
    status_enum.create(op.get_bind(), checkfirst=False)
    with op.batch_alter_table('monitoring', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('SUCCESS', 'FAIL', 'WARNING', name='status'), nullable=True))
        batch_op.add_column(sa.Column('info', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring', schema=None) as batch_op:
        batch_op.drop_column('info')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
