"""create retest & update student year summary

Revision ID: 1f5a2a97fc5d
Revises: 1aceb55740ac
Create Date: 2025-12-10 16:37:06.725572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5a2a97fc5d'
down_revision = '1aceb55740ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('retest_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', 'year_id', name='stu_les_yea_uniq')
    )
    with op.batch_alter_table('student_year_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retest_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_year_summary', schema=None) as batch_op:
        batch_op.drop_column('retest_status')

    op.drop_table('retest')
    # ### end Alembic commands ###
