"""update tmp_token

Revision ID: 1f714caf1d9d
Revises: 14b9c1f96c76
Create Date: 2025-09-27 18:05:43.086582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f714caf1d9d'
down_revision = '14b9c1f96c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmp_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_password_status', sa.Boolean(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmp_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('set_password_status')

    # ### end Alembic commands ###
