"""update students

Revision ID: 20782c0f8463
Revises: 1632370a76ea
Create Date: 2025-10-17 14:27:10.822563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20782c0f8463'
down_revision = '1632370a76ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
