"""update class_room and teacher

Revision ID: 2111647bebd5
Revises: 1890a25878c2
Create Date: 2025-10-01 17:06:18.543491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2111647bebd5'
down_revision = '1890a25878c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('teachers_class_room_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'year', ['year_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('class_room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_room_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teachers_class_room_id_fkey'), 'class_room', ['class_room_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('year_id')

    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))

    with op.batch_alter_table('class_room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
