"""update score type

Revision ID: 211748bcb6ef
Revises: ffb3d347d70b
Create Date: 2025-11-07 16:23:35.283757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211748bcb6ef'
down_revision = 'ffb3d347d70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['score_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
