"""update student period summary remove nullable for class_room_id

Revision ID: 2117d5cf1c18
Revises: d8080d7a315c
Create Date: 2025-11-24 19:43:09.048237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2117d5cf1c18'
down_revision = 'd8080d7a315c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_period_summary', schema=None) as batch_op:
        batch_op.alter_column('class_room_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_period_summary', schema=None) as batch_op:
        batch_op.alter_column('class_room_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
