"""update file foreignkey

Revision ID: 232ff0351ad5
Revises: dde819b1644c
Create Date: 2025-10-16 16:23:46.089699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232ff0351ad5'
down_revision = 'dde819b1644c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('files_folder_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teach_class', ['folder_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('teach_class', schema=None) as batch_op:
        batch_op.alter_column('year_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teach_class', schema=None) as batch_op:
        batch_op.alter_column('year_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('files_folder_id_fkey'), 'class_lesson', ['folder_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
