"""update student lesson period

Revision ID: 2578fac4a7d5
Revises: 6177ee79b830
Create Date: 2025-10-18 23:00:08.298917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2578fac4a7d5'
down_revision = '6177ee79b830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_lesson_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('student_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_oral', sa.Float(), nullable=True),
    sa.Column('score_15m', sa.Float(), nullable=True),
    sa.Column('score_45m', sa.Float(), nullable=True),
    sa.Column('score_final', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['student_lesson_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('student_lesson_period')
    # ### end Alembic commands ###
