"""remove year_id from Teachers

Revision ID: 25f33433d021
Revises: 2111647bebd5
Create Date: 2025-10-01 17:08:28.573765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f33433d021'
down_revision = '2111647bebd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teachers_year_id_fkey'), type_='foreignkey')
        batch_op.drop_column('year_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('teachers_year_id_fkey'), 'year', ['year_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
