"""update score with not null for score

Revision ID: 27077496e3c4
Revises: 8c73bd9dfe2f
Create Date: 2025-12-04 12:38:53.715357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27077496e3c4'
down_revision = '8c73bd9dfe2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
