"""update attendence 

Revision ID: 36294d114e38
Revises: 92764453a42e
Create Date: 2025-12-13 11:50:00.664526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36294d114e38'
down_revision = '92764453a42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'period', ['period_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('period_id')

    # ### end Alembic commands ###
