"""fix grade in class, lesson

Revision ID: 37432fdb3751
Revises: 981decc89a72
Create Date: 2025-11-04 16:18:22.541034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37432fdb3751'
down_revision = '981decc89a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'grade', ['grade'], ['grade'], ondelete='CASCADE')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'grade', ['grade'], ['grade'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade')

    with op.batch_alter_table('class_room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
