"""update monitoring

Revision ID: 37879376f390
Revises: 45f446c2a1dd
Create Date: 2025-09-17 15:05:58.386091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37879376f390'
down_revision = '45f446c2a1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=True))
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
