"""update schedule unique constraint

Revision ID: 3ce57c91a77d
Revises: 6e0f42583924
Create Date: 2025-12-18 17:45:38.046798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce57c91a77d'
down_revision = '6e0f42583924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schedule_uniq'), type_='unique')
        batch_op.create_unique_constraint('schedule_uniq', ['period_id', 'class_room_id', 'day_of_week', 'lesson_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_uniq', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('schedule_uniq'), ['lesson_id', 'period_id', 'class_room_id', 'day_of_week', 'lesson_time'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
