"""update student year summary with correct Unique constraint

Revision ID: 411d69f9fa06
Revises: 54d5933cbfe5
Create Date: 2025-12-21 15:39:23.563148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411d69f9fa06'
down_revision = '54d5933cbfe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_period_summary', schema=None) as batch_op:
        batch_op.create_unique_constraint('stu_per_uniq', ['student_id', 'period_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_period_summary', schema=None) as batch_op:
        batch_op.drop_constraint('stu_per_uniq', type_='unique')

    # ### end Alembic commands ###
