"""update

Revision ID: 429c732011db
Revises: 1a87feec8976
Create Date: 2025-09-12 18:47:30.637947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429c732011db'
down_revision = '1a87feec8976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teach_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('teach_room', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teach_room'], ['class_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teach_room')
    # ### end Alembic commands ###
