"""update monitoring

Revision ID: 45f446c2a1dd
Revises: 0ab2e2fb5a51
Create Date: 2025-09-17 15:01:17.235658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f446c2a1dd'
down_revision = '0ab2e2fb5a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=20)))
        batch_op.drop_constraint(batch_op.f('monitoring_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('monitoring_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
