"""update schedule unique constraint

Revision ID: 54d5933cbfe5
Revises: 81b54b71e54b
Create Date: 2025-12-18 18:19:41.190914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d5933cbfe5'
down_revision = '81b54b71e54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schedule_teacher_uniq'), type_='unique')
        batch_op.create_unique_constraint('schedule_teacher_uniq', ['period_id', 'day_of_week', 'lesson_time', 'teacher_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_teacher_uniq', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('schedule_teacher_uniq'), ['period_id', 'day_of_week', 'lesson_time', 'teacher_id', 'class_room_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
