"""update score 2

Revision ID: 562dd6ea7456
Revises: dc22445ab1bd
Create Date: 2025-11-07 19:33:13.615213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562dd6ea7456'
down_revision = 'dc22445ab1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('attempt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
