"""update attendence note

Revision ID: 59229d5cec99
Revises: c137c49eae2d
Create Date: 2025-12-06 12:21:34.919304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59229d5cec99'
down_revision = 'c137c49eae2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence__note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('class_room_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.drop_constraint(batch_op.f('attendence__note_attendence_id_key'), type_='unique')
        batch_op.create_unique_constraint('stu_date_uniq', ['student_id', 'date'])
        batch_op.drop_constraint(batch_op.f('attendence__note_attendence_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'class_room', ['class_room_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('attendence_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence__note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendence_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendence__note_attendence_id_fkey'), 'attendence', ['attendence_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('stu_date_uniq', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('attendence__note_attendence_id_key'), ['attendence_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('date')
        batch_op.drop_column('class_room_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
