"""create lesson

Revision ID: 5eabb322001e
Revises: 79ff48bdf7ce
Create Date: 2025-09-09 18:18:11.564980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eabb322001e'
down_revision = '79ff48bdf7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.drop_column('lesson')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lesson_id')

    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson', sa.VARCHAR(length=14), autoincrement=False, nullable=False))

    op.drop_table('lesson')
    # ### end Alembic commands ###
