"""refactor student lesson period

Revision ID: 6177ee79b830
Revises: 8844c62f59a6
Create Date: 2025-10-18 20:46:30.849697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6177ee79b830'
down_revision = '8844c62f59a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_lesson_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_lesson_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_lesson_id'], ['student_lesson.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_lesson_id')
    )

    with op.batch_alter_table('student_lesson', schema=None) as batch_op:
        batch_op.drop_column('academicperiod_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academicperiod_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('student_lesson_academicperiod_id_fkey'), 'academicperiod', ['academicperiod_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('academicperiod',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('academicperiod_semester_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], name=op.f('academicperiod_year_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('academicperiod_pkey'))
    )
    op.drop_table('student_lesson_period')
    op.drop_table('period')
    # ### end Alembic commands ###
