"""update attendence with date

Revision ID: 654c2a3e490a
Revises: 36294d114e38
Create Date: 2025-12-13 14:51:59.510206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654c2a3e490a'
down_revision = '36294d114e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
