"""update students and teachers

Revision ID: 79c802085097
Revises: 1f714caf1d9d
Create Date: 2025-09-28 15:41:35.706974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c802085097'
down_revision = '1f714caf1d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_info_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teacher_info_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('teacher_info_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('student_info_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
