"""update students & info

Revision ID: 79ff48bdf7ce
Revises: af265774d31d
Create Date: 2025-09-08 17:56:33.485421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ff48bdf7ce'
down_revision = 'af265774d31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'info', ['info_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('tel')
        batch_op.drop_column('add')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tel', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('info_id')

    # ### end Alembic commands ###
