"""update changed password for users

Revision ID: 7e3a15de87cb
Revises: d2fddf3c2d70
Create Date: 2025-10-17 15:37:45.479869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3a15de87cb'
down_revision = 'd2fddf3c2d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('changed_password')

    # ### end Alembic commands ###
