"""update cloud with class_room_id

Revision ID: 7f2c32a8d1ff
Revises: 5382e5c04b07
Create Date: 2025-10-03 14:51:18.914691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2c32a8d1ff'
down_revision = '5382e5c04b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_room_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('cloud_year_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'class_room', ['class_room_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('year_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cloud_year_id_fkey'), 'year', ['year_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('class_room_id')

    # ### end Alembic commands ###
