"""update schedule unique constraint

Revision ID: 81b54b71e54b
Revises: 3ce57c91a77d
Create Date: 2025-12-18 17:47:58.908905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b54b71e54b'
down_revision = '3ce57c91a77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_unique_constraint('schedule_teacher_uniq', ['period_id', 'day_of_week', 'lesson_time', 'teacher_id', 'class_room_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_teacher_uniq', type_='unique')

    # ### end Alembic commands ###
