"""update attendence & create attendence not

Revision ID: 8244eb842a04
Revises: 27077496e3c4
Create Date: 2025-12-06 11:25:00.110032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8244eb842a04'
down_revision = '27077496e3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendence__note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendence_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['attendence_id'], ['attendence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    op.drop_table('attendence__note')
    # ### end Alembic commands ###
