"""update year

Revision ID: 8844c62f59a6
Revises: aed2643f6672
Create Date: 2025-10-18 12:05:01.106717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8844c62f59a6'
down_revision = 'aed2643f6672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('year', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('year', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
