"""update Lesson tag with is homeroom teacher

Revision ID: 8c73bd9dfe2f
Revises: 10b2e8410f38
Create Date: 2025-11-29 10:53:23.359167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c73bd9dfe2f'
down_revision = '10b2e8410f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessontag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_homeroom_teacher', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessontag', schema=None) as batch_op:
        batch_op.drop_column('is_homeroom_teacher')

    # ### end Alembic commands ###
