"""update schedule

Revision ID: 92764453a42e
Revises: 1f5a2a97fc5d
Create Date: 2025-12-13 11:24:49.207187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92764453a42e'
down_revision = '1f5a2a97fc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('attendence__note')
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('note', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('stu_sch_uniq'), type_='unique')
        batch_op.create_unique_constraint('stu_day_uniq', ['student_id', 'day_of_week'])
        batch_op.drop_constraint(batch_op.f('attendence_schedule_id_fkey'), type_='foreignkey')
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('attendence_schedule_id_fkey'), 'schedule', ['schedule_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('stu_day_uniq', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('stu_sch_uniq'), ['student_id', 'schedule_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('note')
        batch_op.drop_column('day_of_week')

    op.create_table('attendence__note',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_room_id'], ['class_room.id'], name=op.f('attendence__note_class_room_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('attendence__note_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attendence__note_pkey')),
    sa.UniqueConstraint('student_id', 'date', name=op.f('stu_date_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    # ### end Alembic commands ###
