"""update monitoring

Revision ID: 950d49d48fb8
Revises: 1a8071bc7ce4
Create Date: 2025-09-16 15:55:29.544611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950d49d48fb8'
down_revision = '1a8071bc7ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###
