"""update

Revision ID: 981decc89a72
Revises: 
Create Date: 2025-11-04 16:04:25.765743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981decc89a72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_room', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('class_room_grade_id_fkey'), type_='foreignkey')
        batch_op.drop_column('grade_id')

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['grade'])

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_grade_id_fkey'), type_='foreignkey')
        batch_op.drop_column('grade_id')

    with op.batch_alter_table('student_year_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('student_year_summary_grade_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'grade', ['grade'], ['grade'], ondelete='NO ACTION')
        batch_op.drop_column('grade_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_year_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_year_summary_grade_id_fkey'), 'grade', ['grade_id'], ['id'])
        batch_op.drop_column('grade')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('lesson_grade_id_fkey'), 'grade', ['grade_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('class_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('class_room_grade_id_fkey'), 'grade', ['grade_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
