"""update score 4

Revision ID: 9935421c26a3
Revises: dbaf8654acb4
Create Date: 2025-11-09 17:18:27.532690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9935421c26a3'
down_revision = 'dbaf8654acb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_unique_constraint('score_uniq', ['student_lesson_period_id', 'score_type_id', 'attempt'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_constraint('score_uniq', type_='unique')

    # ### end Alembic commands ###
