"""update cloud for folder

Revision ID: 9b1d283dfa43
Revises: 37879376f390
Create Date: 2025-09-20 21:19:03.237745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1d283dfa43'
down_revision = '37879376f390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.drop_column('folder')

    # ### end Alembic commands ###
