"""update schedule remove nullable of teacher id

Revision ID: a0e341e622b4
Revises: 9b988b4627aa
Create Date: 2025-11-20 17:05:03.164147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e341e622b4'
down_revision = '9b988b4627aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('unq_cls_period'), type_='unique')
        batch_op.create_unique_constraint('cls_period_day_les_uniq', ['class_room_id', 'period_id', 'day_of_week', 'lesson_time'])
        batch_op.create_unique_constraint('tea_per_day_les_uniq', ['teacher_id', 'period_id', 'day_of_week', 'lesson_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('tea_per_day_les_uniq', type_='unique')
        batch_op.drop_constraint('cls_period_day_les_uniq', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unq_cls_period'), ['class_room_id', 'period_id', 'day_of_week', 'lesson_time'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
