"""create sub table for student lesson

Revision ID: aed2643f6672
Revises: 7e3a15de87cb
Create Date: 2025-10-17 22:05:49.777220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed2643f6672'
down_revision = '7e3a15de87cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academicperiod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academicperiod_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academicperiod_id'], ['academicperiod.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_lesson_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('score_semester_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('score_student_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('score_lesson_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('score_year_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_lesson', ['student_lesson_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('year_id')
        batch_op.drop_column('semester_id')
        batch_op.drop_column('lesson_id')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('semester_year_id_fkey'), type_='foreignkey')
        batch_op.drop_column('year_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('semester_year_id_fkey'), 'year', ['year_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('year_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('score_year_id_fkey'), 'year', ['year_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('score_lesson_id_fkey'), 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('score_student_id_fkey'), 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('score_semester_id_fkey'), 'semester', ['semester_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('student_lesson_id')

    op.drop_table('student_lesson')
    op.drop_table('academicperiod')
    # ### end Alembic commands ###
