"""update info

Revision ID: af265774d31d
Revises: 78596d7b31b3
Create Date: 2025-09-08 15:58:33.201137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af265774d31d'
down_revision = '78596d7b31b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'class_room', ['class_room_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('class_room')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_room', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('class_room_id')

    # ### end Alembic commands ###
