"""update Student_Lesson_Period

Revision ID: baf30654d69c
Revises: 562dd6ea7456
Create Date: 2025-11-07 21:47:20.231677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf30654d69c'
down_revision = '562dd6ea7456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_lesson_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_lesson_period', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
