"""update schedule unique constraint

Revision ID: bbe1805940f8
Revises: e5c05bebc860
Create Date: 2025-12-18 17:39:50.891973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe1805940f8'
down_revision = 'e5c05bebc860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schedule_uniq'), type_='unique')
        batch_op.create_unique_constraint('schedule_uniq', ['teacher_id', 'period_id', 'class_room_id', 'day_of_week', 'lesson_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_uniq', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('schedule_uniq'), ['teacher_id', 'period_id', 'lesson_id', 'class_room_id', 'day_of_week', 'lesson_time'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
