"""update unique to attendence_id for attendence note

Revision ID: c137c49eae2d
Revises: 8244eb842a04
Create Date: 2025-12-06 11:38:15.910065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c137c49eae2d'
down_revision = '8244eb842a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence__note', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['attendence_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence__note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
