"""update student period summary

Revision ID: d8080d7a315c
Revises: a0e341e622b4
Create Date: 2025-11-24 18:55:12.921107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8080d7a315c'
down_revision = 'a0e341e622b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_period_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'grade', ['grade'], ['grade'], ondelete='NO ACTION')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_period_summary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
