"""update teach class with year_id

Revision ID: dde819b1644c
Revises: a6b9d5dee5be
Create Date: 2025-10-14 22:51:56.267616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde819b1644c'
down_revision = 'a6b9d5dee5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teach_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_id', sa.Integer(), nullable=True))
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'year', ['year_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teach_class', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('year_id')

    # ### end Alembic commands ###
