"""update schedule unique constraint, lesson remove is_homeroom_teacher

Revision ID: e5c05bebc860
Revises: ff85d6a4d48d
Create Date: 2025-12-18 12:16:21.569018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c05bebc860'
down_revision = 'ff85d6a4d48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessontag', schema=None) as batch_op:
        batch_op.drop_column('is_homeroom_teacher')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cls_period_day_les_uniq'), type_='unique')
        batch_op.drop_constraint(batch_op.f('tea_per_day_les_uniq'), type_='unique')
        batch_op.create_unique_constraint('schedule_uniq', ['teacher_id', 'period_id', 'lesson_id', 'class_room_id', 'day_of_week', 'lesson_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_uniq', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('tea_per_day_les_uniq'), ['teacher_id', 'period_id', 'day_of_week', 'lesson_time'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('cls_period_day_les_uniq'), ['class_room_id', 'period_id', 'day_of_week', 'lesson_time'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('lessontag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_homeroom_teacher', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
