"""update semester with weight

Revision ID: f76bc2712e6d
Revises: 59229d5cec99
Create Date: 2025-12-07 17:34:34.333288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76bc2712e6d'
down_revision = '59229d5cec99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
