"""update Score

Revision ID: f89aadfeea3a
Revises: baf30654d69c
Create Date: 2025-11-07 21:59:56.323875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89aadfeea3a'
down_revision = 'baf30654d69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_type', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('score_score_type_id_fkey'), type_='foreignkey')
        batch_op.drop_column('score_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('score_score_type_id_fkey'), 'score_type', ['score_type_id'], ['id'])
        batch_op.drop_column('score_type')

    # ### end Alembic commands ###
