"""update cloud

Revision ID: f934f65b97a7
Revises: 429c732011db
Create Date: 2025-09-14 19:53:18.306428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f934f65b97a7'
down_revision = '429c732011db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.alter_column('upload_by',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Integer(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['upload_by'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('upload_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
