"""update attendence with remove day of week

Revision ID: fb6cd67502e6
Revises: 654c2a3e490a
Create Date: 2025-12-13 22:29:17.616412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6cd67502e6'
down_revision = '654c2a3e490a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('stu_day_uniq'), type_='unique')
        batch_op.create_unique_constraint('stu_date_uniq', ['student_id', 'date'])
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('stu_date_uniq', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('stu_day_uniq'), ['student_id', 'day_of_week'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
