"""update student year summary with is new student

Revision ID: ff85d6a4d48d
Revises: fb6cd67502e6
Create Date: 2025-12-16 12:43:54.633052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff85d6a4d48d'
down_revision = 'fb6cd67502e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_year_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new_student', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_year_summary', schema=None) as batch_op:
        batch_op.drop_column('is_new_student')

    # ### end Alembic commands ###
