"""create score type

Revision ID: ffb3d347d70b
Revises: e8ad6f36a07e
Create Date: 2025-11-07 16:15:40.518178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb3d347d70b'
down_revision = 'e8ad6f36a07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_type', sa.String(length=15), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'score_type', ['score_type_id'], ['id'], ondelete='NO ACTION')
        batch_op.drop_column('rate')
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('score_type_id')

    op.drop_table('score_type')
    # ### end Alembic commands ###
