"""update users

Revision ID: ffe56d1737dd
Revises: acde44ed5f64
Create Date: 2025-09-27 13:19:09.656180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe56d1737dd'
down_revision = 'acde44ed5f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('token_expire', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('token_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_status')
        batch_op.drop_column('token_expire')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
